version: '3.8'

services:
  magic-math-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: magic-math-api
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - REDIS_URL=redis://redis:6379
      - CACHE_TTL=3600
      - RATE_LIMIT_MAX=100
      - RATE_LIMIT_WINDOW=60000
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./main.ts:/app/main.ts
      - ./deno.json:/app/deno.json
      - deno-cache:/deno-dir/deps
    command: ["run", "--allow-net", "--allow-env", "--allow-read", "--watch", "main.ts"]
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: magic-math-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  deno-cache:
    name: deno-cache
  redis-data:
    name: redis-data 