version: '3.8'

services:
  magic-math-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: magic-math-api
    ports:
      - "8080:5000"
    environment:
      - PORT=5000
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./main.ts:/app/main.ts
      - ./deno.json:/app/deno.json
      - deno-cache:/deno-dir/deps
    command: ["run", "--allow-net", "--allow-env", "--allow-read", "--watch", "main.ts"]

volumes:
  deno-cache:
    name: deno-cache 