name: Magic Math API CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.37.x
          
      - name: Verify formatting
        run: deno fmt --check
        
      - name: Run linter
        run: deno lint
        
      - name: Run tests
        run: deno task test
        
      - name: Run algorithm tests
        run: deno task test:algorithms
        
      - name: Run API tests
        run: deno task test:api
        
      - name: Run benchmarks
        run: deno task benchmark
  
  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: magic-math-api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  
  # Uncomment and configure this job for automated deployment
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
  #   
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #       
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2
  #       
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  #         
  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v4
  #       with:
  #         context: .
  #         push: true
  #         tags: yourusername/magic-math-api:latest
  #         
  #     # Add deployment steps for your specific hosting platform
  #     # Examples: AWS ECS, Google Cloud Run, Azure Container Instances, etc. 